[build]
cmd = "pip install -r requirements.txt"

[deploy]
startCommand = "python server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ENVIRONMENT = "production"
PORT = "8001"

[healthcheck]
path = "/api/health"
timeout = 30
interval = 60

[domains]
# Custom domain configuration
# Add your custom domains here when ready